name: Deploy to GH Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Vuepress ./dist
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm --prefix docs ci
      - run: npm --prefix run build

      - name: Commit the result of ./dist to gh-pages branch
        run: |
          cd ./docs/.vuepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Deployed with GitHub Actions"

      - name: Force push the commit to the gh-pages branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vuepress/dist
